import KanadeRussell.Heisenberg.PolynomialGrading

/-! Vacuum grades of tensor cyclic modules generated by homogeneous vacuum seeds. -/
set_option backward.isDefEq.respectTransparency false
namespace KanadeRussell.Heisenberg
open Tsuchioka Tsuchioka.Fock
variable {K : Type*} [Field K] [CharZero K]

noncomputable def shiftedTensorVacuumGrade (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (n : ℕ) : Submodule K (tensorCyclicSpan w seed) :=
  (tensorCyclicGrading w hw seed).grade (d+n) ⊓
    vacuum (tensorCyclicGrading w hw seed).annihilate

theorem shiftedTensorVacuumGrade_map (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (n : ℕ) :
    (shiftedTensorVacuumGrade w hw seed d n).map (tensorCyclicSpan w seed).subtype =
      (tensorCyclicSpan w seed ⊓ heisenbergVacuum w) ⊓ grade (d+n) := by
  unfold shiftedTensorVacuumGrade
  rw [tensorCyclicGrading_vacuum]
  change ((grade (d+n)).comap (tensorCyclicSpan w seed).subtype ⊓
    (heisenbergVacuum w).comap (tensorCyclicSpan w seed).subtype).map _ = _
  rw [← Submodule.comap_inf, Submodule.map_comap_subtype]
  ac_rfl

theorem shiftedTensorVacuumGrade_map_eq_firstWordSpan (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hv : seed ∈ heisenbergVacuum w)
    (hd : seed ∈ grade d) (n : ℕ) :
    (shiftedTensorVacuumGrade w hw seed d n).map (tensorCyclicSpan w seed).subtype =
      firstWordSpan w seed (-(n:ℤ)) := by
  rw [shiftedTensorVacuumGrade_map,
    tensorCyclicSpan_inf_vacuum_eq_zCyclicSpan w hw seed hv,
    zCyclicSpan_inf_grade_eq_firstWordSpan w hw seed d (d+n) hd]
  congr 1
  omega

theorem shiftedTensorVacuumGrade_finrank_eq (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hv : seed ∈ heisenbergVacuum w)
    (hd : seed ∈ grade d) (n : ℕ) :
    Module.finrank K (shiftedTensorVacuumGrade w hw seed d n) =
      Module.finrank K (firstWordSpan w seed (-(n:ℤ))) := by
  have h := (Submodule.equivMapOfInjective (tensorCyclicSpan w seed).subtype
    (tensorCyclicSpan w seed).subtype_injective
    (shiftedTensorVacuumGrade w hw seed d n)).finrank_eq
  rwa [shiftedTensorVacuumGrade_map_eq_firstWordSpan w hw seed d hv hd n] at h

theorem shiftedTensorVacuumGrade_finite (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hv : seed ∈ heisenbergVacuum w)
    (hd : seed ∈ grade d) (n : ℕ)
    [Module.Finite K (firstWordSpan w seed (-(n:ℤ)))] :
    Module.Finite K (shiftedTensorVacuumGrade w hw seed d n) := by
  letI : Module.Finite K ((shiftedTensorVacuumGrade w hw seed d n).map
      (tensorCyclicSpan w seed).subtype) := by
    rw [shiftedTensorVacuumGrade_map_eq_firstWordSpan w hw seed d hv hd n]
    infer_instance
  exact Module.Finite.of_injective
    (Submodule.equivMapOfInjective (tensorCyclicSpan w seed).subtype
      (tensorCyclicSpan w seed).subtype_injective
      (shiftedTensorVacuumGrade w hw seed d n)).toLinearMap
    (Submodule.equivMapOfInjective (tensorCyclicSpan w seed).subtype
      (tensorCyclicSpan w seed).subtype_injective
      (shiftedTensorVacuumGrade w hw seed d n)).injective

end KanadeRussell.Heisenberg
