import KanadeRussell.Sectors.SkewCyclicity

/-! A strict boundary in the character argument: the entire polynomial
Heisenberg vacuum is larger than the cyclic vacuum generated by 1.
The degree-one skew seed is an explicit witness. -/
set_option backward.isDefEq.respectTransparency false
namespace KanadeRussell.Sectors
open Tsuchioka Tsuchioka.Fock
variable {K : Type*} [Field K] [CharZero K]

theorem permute_vacuum_word (w : K) (σ : Equiv.Perm (Fin 3)) (u : Word) :
    permute σ ((highestWeightAction w).wordOperator u 1) =
      (highestWeightAction w).wordOperator u 1 := by
  induction u with
  | nil => exact map_one _
  | cons i u ih =>
    change permute σ (mode w i ((highestWeightAction w).wordOperator u 1)) = _
    rw [permute_mode, ih]
    rfl

theorem permute_firstCyclicSpan_vacuum (w : K) (σ : Equiv.Perm (Fin 3))
    (f : Space K) (hf : f ∈ firstCyclicSpan w 1) : permute σ f = f := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨u,rfl⟩ := hf
    exact permute_vacuum_word w σ u
  | zero => exact map_zero _
  | add f g hf hg hif hig => rw [map_add, hif, hig]
  | smul c f hf hi => rw [map_smul, hi]

theorem skewSeed_not_mem_firstCyclicSpan (w : K) :
    skewSeed (K := K) ∉ firstCyclicSpan w 1 := by
  intro h
  have hfix := permute_firstCyclicSpan_vacuum w swap01 skewSeed h
  have hneg := (mem_skewSpace (skewSeed (K := K))).mp skewSeed_mem
  have he : (2:K) • skewSeed (K := K) = 0 := by
    rw [two_smul]
    exact add_eq_zero_iff_eq_neg.mpr (hfix.symm.trans hneg)
  exact skewSeed_ne_zero ((smul_eq_zero.mp he).resolve_left (by norm_num))

theorem skewSeed_not_mem_zCyclicSpan (w : K) (hw : w^4-w^2+1=0) :
    skewSeed (K := K) ∉ zCyclicSpan w 1 := by
  rw [zCyclicSpan_eq_firstCyclicSpan w hw 1 0
    (MvPolynomial.isWeightedHomogeneous_one K variableWeight)]
  exact skewSeed_not_mem_firstCyclicSpan w

/-- Counting the entire relative polynomial ring cannot compute this cyclic character. -/
theorem zCyclicSpan_vacuum_lt_heisenbergVacuum (w : K) (hw : w^4-w^2+1=0) :
    zCyclicSpan w (1 : Space K) < heisenbergVacuum w := by
  apply lt_of_le_of_ne (zCyclicSpan_le_heisenbergVacuum w 1 (one_mem_heisenbergVacuum w))
  intro he
  exact skewSeed_not_mem_zCyclicSpan w hw (he.symm ▸ skewSeed_heisenbergVacuum w)

theorem tensorCyclicVacuum_lt_heisenbergVacuum (w : K) (hw : w^4-w^2+1=0) :
    tensorCyclicSpan w (1 : Space K) ⊓ heisenbergVacuum w < heisenbergVacuum w := by
  rw [tensorCyclicSpan_inf_vacuum_eq_zCyclicSpan w hw 1 (one_mem_heisenbergVacuum w)]
  exact zCyclicSpan_vacuum_lt_heisenbergVacuum w hw

end KanadeRussell.Sectors
