import KanadeRussell.Representation.HeisenbergGeneration
import KanadeRussell.Tsuchioka.AffinePrincipalDegree

/-! For a homogeneous seed, the tensor cyclic space is precisely the space
generated by the concrete Chevalley operators. -/
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 1200000
namespace KanadeRussell.Tsuchioka.Fock
attribute [local instance] LieRing.ofAssociativeRing
open RootData (simpleRoot)
variable {K : Type*} [Field K] [CharZero K]

theorem tensorRootMode_mem_chevalley (w : K) (hw : w^4-w^2+1=0)
    (β : RootData.Root) (n : ℤ) : tensorRootMode w β.val n ∈ chevalleyOperatorAlgebra w := by
  obtain ⟨r,p,hp⟩ := RootData.isRoot_mem_orbits β.val β.property
  rw [hp]
  have heq : tensorRootMode w (RootData.orbitRoot r p) n =
      w ^ ((p.val:ℤ)*n) • tensorRootMode w (RootData.orbitRepresentative r) n := by
    apply LinearMap.ext
    intro f
    exact tensorRootMode_iterate w hw _ p.val n f
  rw [heq]
  apply (chevalleyOperatorAlgebra w).smul_mem
  have h := simple_tensor_mode_mem_chevalley w hw r n
  fin_cases r <;> simpa [RootData.orbitRepresentative] using h

theorem heisenbergMode_mem_tensorOperatorAlgebra (w : K) (n : ℤ) :
    heisenbergMode w n ∈ tensorOperatorAlgebra w := by
  unfold heisenbergMode
  split
  · split
    · exact heisenbergPositive_mem_tensorOperatorAlgebra w _
    · exact heisenbergNegative_mem_tensorOperatorAlgebra w _
  · exact (tensorOperatorAlgebra w).zero_mem

theorem tensorModeEvaluate_mem_tensorOperatorAlgebra (w : K) (n : ℤ) (c : Fin 4 → K) :
    tensorModeEvaluate w n c ∈ tensorOperatorAlgebra w := by
  rw [tensorModeEvaluate_apply]
  apply (tensorOperatorAlgebra w).add_mem
  · apply (tensorOperatorAlgebra w).add_mem
    · exact (tensorOperatorAlgebra w).add_mem
        ((tensorOperatorAlgebra w).smul_mem
          (tensorRootMode_mem_tensorOperatorAlgebra w RootData.firstRoot n) _)
        ((tensorOperatorAlgebra w).smul_mem
          (tensorRootMode_mem_tensorOperatorAlgebra w RootData.secondRoot n) _)
    · exact (tensorOperatorAlgebra w).smul_mem (heisenbergMode_mem_tensorOperatorAlgebra w n) _
  · exact (tensorOperatorAlgebra w).smul_mem (tensorOperatorAlgebra w).one_mem _

theorem chevalleyOperatorAlgebra_le_tensor (w : K) :
    chevalleyOperatorAlgebra w ≤ tensorOperatorAlgebra w := by
  apply Algebra.adjoin_le
  rintro _ (⟨i,rfl⟩ | ⟨i,rfl⟩ | ⟨i,rfl⟩) <;>
    exact tensorModeEvaluate_mem_tensorOperatorAlgebra w _ _

noncomputable def chevalleyCyclicSpan (w : K) (seed : Space K) : Submodule K (Space K) :=
  Submodule.span K ((fun a : Module.End K (Space K) => a seed) ''
    (chevalleyOperatorAlgebra w : Set (Module.End K (Space K))))

theorem chevalleyCyclicSpan_seed (w : K) (seed : Space K) : seed ∈ chevalleyCyclicSpan w seed :=
  Submodule.subset_span ⟨1,(chevalleyOperatorAlgebra w).one_mem,rfl⟩

theorem chevalleyCyclicSpan_algebra_mem (w : K) (seed : Space K)
    (a : Module.End K (Space K)) (ha : a ∈ chevalleyOperatorAlgebra w)
    (f : Space K) (hf : f ∈ chevalleyCyclicSpan w seed) : a f ∈ chevalleyCyclicSpan w seed := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨b,hb,rfl⟩ := hf
    exact Submodule.subset_span ⟨a*b,(chevalleyOperatorAlgebra w).mul_mem ha hb,rfl⟩
  | zero => simp
  | add f g hf hg hif hig => simpa only [map_add] using (chevalleyCyclicSpan w seed).add_mem hif hig
  | smul c f hf hi => simpa only [map_smul] using (chevalleyCyclicSpan w seed).smul_mem c hi

theorem chevalleyCyclicSpan_le_tensor (w : K) (seed : Space K) :
    chevalleyCyclicSpan w seed ≤ tensorCyclicSpan w seed := by
  apply Submodule.span_le.mpr
  rintro _ ⟨a,ha,rfl⟩
  exact Submodule.subset_span ⟨a,chevalleyOperatorAlgebra_le_tensor w ha,rfl⟩

theorem principalDerivation_lie_mem_chevalley (w : K)
    (a : Module.End K (Space K)) (ha : a ∈ chevalleyOperatorAlgebra w) :
    ⁅principalDerivation (K:=K),a⁆ ∈ chevalleyOperatorAlgebra w := by
  induction ha using Algebra.adjoin_induction with
  | mem a ha =>
    rcases ha with ⟨i,rfl⟩ | ⟨i,rfl⟩ | ⟨i,rfl⟩
    · rw [principalDerivation_chevalleyE]; exact chevalleyE_mem_algebra w i
    · rw [principalDerivation_chevalleyF]; exact (chevalleyOperatorAlgebra w).neg_mem (chevalleyF_mem_algebra w i)
    · rw [principalDerivation_chevalleyH]; exact (chevalleyOperatorAlgebra w).zero_mem
  | algebraMap c =>
    have hz : ⁅principalDerivation (K:=K), algebraMap K (Module.End K (Space K)) c⁆ = 0 := by
      simp [Ring.lie_def, Algebra.commutes]
    rw [hz]; exact (chevalleyOperatorAlgebra w).zero_mem
  | add a b ha hb hia hib =>
    rw [lie_add]; exact (chevalleyOperatorAlgebra w).add_mem hia hib
  | mul a b ha hb hia hib =>
    have heq : ⁅principalDerivation (K:=K),a*b⁆ = ⁅principalDerivation (K:=K),a⁆*b + a*⁅principalDerivation (K:=K),b⁆ := by
      simp only [Ring.lie_def, mul_sub, sub_mul, mul_assoc]
      abel
    rw [heq]
    exact (chevalleyOperatorAlgebra w).add_mem
      ((chevalleyOperatorAlgebra w).mul_mem hia hb) ((chevalleyOperatorAlgebra w).mul_mem ha hib)

theorem principalDerivation_mem_chevalleyCyclicSpan (w : K) (seed : Space K)
    (d : ℤ) (hseed : seed ∈ grade d) (f : Space K) (hf : f ∈ chevalleyCyclicSpan w seed) :
    principalDerivation f ∈ chevalleyCyclicSpan w seed := by
  have hds : principalDerivation seed = -(d:K) • seed := by
    simp only [principalDerivation, LinearMap.neg_apply, degreeOperator_eq_of_grade d seed hseed, neg_smul]
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨a,ha,rfl⟩ := hf
    have h1 : (⁅principalDerivation (K:=K),a⁆) seed ∈ chevalleyCyclicSpan w seed :=
      Submodule.subset_span ⟨_,principalDerivation_lie_mem_chevalley w a ha,rfl⟩
    have h2 : a (principalDerivation seed) ∈ chevalleyCyclicSpan w seed := by
      rw [hds,map_smul]
      exact (chevalleyCyclicSpan w seed).smul_mem _ (Submodule.subset_span ⟨a,ha,rfl⟩)
    have heq : principalDerivation (a seed) = (⁅principalDerivation (K:=K),a⁆) seed + a (principalDerivation seed) := by
      simp [Ring.lie_def, Module.End.mul_apply]
    rw [heq]
    exact (chevalleyCyclicSpan w seed).add_mem h1 h2
  | zero => simp
  | add f g hf hg hif hig => simpa only [map_add] using (chevalleyCyclicSpan w seed).add_mem hif hig
  | smul c f hf hi => simpa only [map_smul] using (chevalleyCyclicSpan w seed).smul_mem c hi

theorem tensorOperatorAlgebra_preserves_chevalleyCyclicSpan (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hseed : seed ∈ grade d)
    (a : Module.End K (Space K)) (ha : a ∈ tensorOperatorAlgebra w) :
    ∀ f ∈ chevalleyCyclicSpan w seed, a f ∈ chevalleyCyclicSpan w seed := by
  induction ha using Algebra.adjoin_induction with
  | mem a ha =>
    intro f hf
    rcases ha with hx | hp | hn
    · rcases hx with ⟨⟨β,i⟩,rfl⟩ | hd
      · exact chevalleyCyclicSpan_algebra_mem w seed _ (tensorRootMode_mem_chevalley w hw β i) f hf
      · simp only [Set.mem_insert_iff,Set.mem_singleton_iff] at hd
        rcases hd with rfl | rfl
        · exact (chevalleyCyclicSpan w seed).smul_mem 3 hf
        · exact principalDerivation_mem_chevalleyCyclicSpan w seed d hseed f hf
    · obtain ⟨n,rfl⟩ := hp
      exact chevalleyCyclicSpan_algebra_mem w seed _
        (by rw [← heisenbergMode_positive]; exact heisenbergMode_mem_chevalley w hw _) f hf
    · obtain ⟨n,rfl⟩ := hn
      exact chevalleyCyclicSpan_algebra_mem w seed _
        (by rw [← heisenbergMode_negative w]; exact heisenbergMode_mem_chevalley w hw _) f hf
  | algebraMap c =>
    intro f hf
    exact (chevalleyCyclicSpan w seed).smul_mem c hf
  | add a b ha hb hia hib =>
    intro f hf
    exact (chevalleyCyclicSpan w seed).add_mem (hia f hf) (hib f hf)
  | mul a b ha hb hia hib =>
    intro f hf
    exact hia _ (hib f hf)

/-- Both inclusions are proved; this is not just stability under Chevalley generators. -/
theorem chevalleyCyclicSpan_eq_tensor (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hseed : seed ∈ grade d) :
    chevalleyCyclicSpan w seed = tensorCyclicSpan w seed := by
  apply le_antisymm (chevalleyCyclicSpan_le_tensor w seed)
  apply Submodule.span_le.mpr
  rintro _ ⟨a,ha,rfl⟩
  exact tensorOperatorAlgebra_preserves_chevalleyCyclicSpan w hw seed d hseed a ha seed
    (chevalleyCyclicSpan_seed w seed)

theorem chevalleyCyclicSpan_one_eq_tensor (w : K) (hw : w^4-w^2+1=0) :
    chevalleyCyclicSpan w (1 : Space K) = tensorCyclicSpan w 1 :=
  chevalleyCyclicSpan_eq_tensor w hw 1 0 (MvPolynomial.isWeightedHomogeneous_one K variableWeight)

end KanadeRussell.Tsuchioka.Fock
