import KanadeRussell.Representation.LocalNilpotence
import KanadeRussell.Representation.AffineCyclicity
import Mathlib.LinearAlgebra.Eigenspace.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-! Local nilpotence on algebraic cyclic spans, propagated from generator commutators. -/
set_option backward.isDefEq.respectTransparency false
namespace KanadeRussell.Representation
attribute [local instance 100] LieRing.ofAssociativeRing
variable {K V : Type*} [CommRing K] [AddCommGroup V] [Module K V]

noncomputable def locallyNilpotentVectors (f : Module.End K V) : Submodule K V :=
  f.genEigenspace 0 ⊤

@[simp] theorem mem_locallyNilpotentVectors (f : Module.End K V) (v : V) :
    v ∈ locallyNilpotentVectors f ↔ ∃ n : ℕ, (f^n) v = 0 := by
  simp [locallyNilpotentVectors]

theorem locallyNilpotentVectors_stable (f g : Module.End K V)
    (hg : ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K V) f)^r) g = 0)
    (v : V) (hv : v ∈ locallyNilpotentVectors f) : g v ∈ locallyNilpotentVectors f := by
  rw [mem_locallyNilpotentVectors] at hv ⊢
  exact locally_nilpotent_apply_of_ad f g v hg hv

/-- Each generator has a finite adjoint orbit; the exponent can depend on the generator.
The resulting invariant submodule consists of vectors with their own finite annihilation bound. -/
theorem locallyNilpotentVectors_algebra_stable (f : Module.End K V)
    (G : Set (Module.End K V))
    (hG : ∀ g ∈ G, ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K V) f)^r) g = 0)
    (a : Module.End K V) (ha : a ∈ Algebra.adjoin K G) :
    ∀ v ∈ locallyNilpotentVectors f, a v ∈ locallyNilpotentVectors f := by
  induction ha using Algebra.adjoin_induction with
  | mem g hg => exact locallyNilpotentVectors_stable f g (hG g hg)
  | algebraMap c =>
    intro v hv
    exact (locallyNilpotentVectors f).smul_mem c hv
  | add a b ha hb hia hib =>
    intro v hv
    exact (locallyNilpotentVectors f).add_mem (hia v hv) (hib v hv)
  | mul a b ha hb hia hib =>
    intro v hv
    exact hia _ (hib v hv)

/-- Local nilpotence on the seed propagates to the entire cyclic span generated by G. -/
theorem cyclicSpan_le_locallyNilpotentVectors (f : Module.End K V)
    (G : Set (Module.End K V))
    (hG : ∀ g ∈ G, ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K V) f)^r) g = 0)
    (seed : V) (hseed : ∃ s : ℕ, (f^s) seed = 0) :
    Submodule.span K ((fun a : Module.End K V => a seed) ''
      (Algebra.adjoin K G : Set (Module.End K V))) ≤ locallyNilpotentVectors f := by
  apply Submodule.span_le.mpr
  rintro _ ⟨a, ha, rfl⟩
  exact locallyNilpotentVectors_algebra_stable f G hG a ha seed
    ((mem_locallyNilpotentVectors f seed).mpr hseed)

theorem locally_nilpotent_on_cyclicSpan (f : Module.End K V)
    (G : Set (Module.End K V))
    (hG : ∀ g ∈ G, ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K V) f)^r) g = 0)
    (seed : V) (hseed : ∃ s : ℕ, (f^s) seed = 0)
    (v : V) (hv : v ∈ Submodule.span K ((fun a : Module.End K V => a seed) ''
      (Algebra.adjoin K G : Set (Module.End K V)))) : ∃ n : ℕ, (f^n) v = 0 :=
  (mem_locallyNilpotentVectors f v).mp
    (cyclicSpan_le_locallyNilpotentVectors f G hG seed hseed hv)

end KanadeRussell.Representation

namespace KanadeRussell.Tsuchioka.Fock
open KanadeRussell.Representation
attribute [local instance 100] LieRing.ofAssociativeRing
variable {K : Type*} [Field K] [CharZero K]

/-- Serre gives a finite adjoint bound on every negative generator, including itself. -/
theorem chevalleyF_ad_nilpotent_F (w : K) (hw : w^4-w^2+1=0) (i j : Fin 3) :
    ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K (Space K)) (chevalleyF w i))^r)
      (chevalleyF w j) = 0 := by
  refine ⟨(-affineCartanMatrix i j).toNat+1, ?_⟩
  simpa only [pow_succ, Module.End.mul_apply, LieAlgebra.ad_apply] using chevalley_serreF w hw i j

theorem chevalleyF_ad_nilpotent_H (w : K) (hw : w^4-w^2+1=0) (i j : Fin 3) :
    ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K (Space K)) (chevalleyF w i))^r)
      (chevalleyH w j) = 0 := by
  refine ⟨2, ?_⟩
  simp only [pow_succ, pow_zero, Module.End.mul_apply, Module.End.one_apply, LieAlgebra.ad_apply]
  rw [← lie_skew (chevalleyF w i) (chevalleyH w j), chevalley_HF w hw j i]
  apply LinearMap.ext
  intro v
  simp [Ring.lie_def, Module.End.mul_apply, map_smul]

theorem chevalleyF_ad_nilpotent_E (w : K) (hw : w^4-w^2+1=0) (i j : Fin 3) :
    ∃ r : ℕ, ((LieAlgebra.ad K (Module.End K (Space K)) (chevalleyF w i))^r)
      (chevalleyE w j) = 0 := by
  refine ⟨3, ?_⟩
  simp only [pow_succ, pow_zero, Module.End.mul_apply, Module.End.one_apply, LieAlgebra.ad_apply]
  rw [← lie_skew (chevalleyF w i) (chevalleyE w j), chevalley_EF w hw j i]
  by_cases hij : j = i
  · subst j
    simp only [if_true, lie_neg]
    rw [← lie_skew (chevalleyF w i) (chevalleyH w i), chevalley_HF w hw i i]
    apply LinearMap.ext
    intro v
    simp [Ring.lie_def, Module.End.mul_apply, map_smul]
  · simp [hij]

/-- A seed annihilated by some power of F_i generates an entire locally nilpotent
F_i-module. Adjoint nilpotence on all nine generators is proved from EF, HF and Serre. -/
theorem chevalleyF_locally_nilpotent_on_cyclicSpan (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (i : Fin 3) (hseed : ∃ s : ℕ, ((chevalleyF w i)^s) seed = 0)
    (v : Space K) (hv : v ∈ chevalleyCyclicSpan w seed) :
    ∃ n : ℕ, ((chevalleyF w i)^n) v = 0 := by
  apply locally_nilpotent_on_cyclicSpan (chevalleyF w i)
    (Set.range (chevalleyE w) ∪ (Set.range (chevalleyF w) ∪ Set.range (chevalleyH w)))
    _ seed hseed v hv
  rintro _ (⟨j,rfl⟩ | ⟨j,rfl⟩ | ⟨j,rfl⟩)
  · exact chevalleyF_ad_nilpotent_E w hw i j
  · exact chevalleyF_ad_nilpotent_F w hw i j
  · exact chevalleyF_ad_nilpotent_H w hw i j

theorem chevalleyF_locally_nilpotent_on_tensorCyclicSpan (w : K) (hw : w^4-w^2+1=0)
    (seed : Space K) (d : ℤ) (hd : seed ∈ grade d) (i : Fin 3)
    (hseed : ∃ s : ℕ, ((chevalleyF w i)^s) seed = 0)
    (v : Space K) (hv : v ∈ tensorCyclicSpan w seed) :
    ∃ n : ℕ, ((chevalleyF w i)^n) v = 0 := by
  rw [← chevalleyCyclicSpan_eq_tensor w hw seed d hd] at hv
  exact chevalleyF_locally_nilpotent_on_cyclicSpan w hw seed i hseed v hv

end KanadeRussell.Tsuchioka.Fock
