import KanadeRussell.Representation.ChevalleyInverse
import KanadeRussell.Tsuchioka.TensorCyclicity

/-! Every principal Heisenberg mode belongs to the algebra generated by the
concrete Chevalley operators. No standard-module theorem is used. -/
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 1200000
namespace KanadeRussell.Tsuchioka.Fock
attribute [local instance] LieRing.ofAssociativeRing
open RootData (simpleRoot rootWeight)
variable {K : Type*} [Field K] [CharZero K]

noncomputable def chevalleyOperatorAlgebra (w : K) : Subalgebra K (Module.End K (Space K)) :=
  Algebra.adjoin K (Set.range (chevalleyE w) ∪ (Set.range (chevalleyF w) ∪ Set.range (chevalleyH w)))

theorem chevalleyE_mem_algebra (w : K) (i : Fin 3) : chevalleyE w i ∈ chevalleyOperatorAlgebra w :=
  Algebra.subset_adjoin (Or.inl ⟨i,rfl⟩)
theorem chevalleyF_mem_algebra (w : K) (i : Fin 3) : chevalleyF w i ∈ chevalleyOperatorAlgebra w :=
  Algebra.subset_adjoin (Or.inr (Or.inl ⟨i,rfl⟩))
theorem chevalleyH_mem_algebra (w : K) (i : Fin 3) : chevalleyH w i ∈ chevalleyOperatorAlgebra w :=
  Algebra.subset_adjoin (Or.inr (Or.inr ⟨i,rfl⟩))

omit [CharZero K] in
private theorem bracket_mem (A : Subalgebra K (Module.End K (Space K)))
    {x y : Module.End K (Space K)} (hx : x ∈ A) (hy : y ∈ A) : ⁅x,y⁆ ∈ A :=
  A.sub_mem (A.mul_mem hx hy) (A.mul_mem hy hx)

omit [CharZero K] in
private theorem of_smul_mem (A : Subalgebra K (Module.End K (Space K)))
    (c : K) (hc : c ≠ 0) (x : Module.End K (Space K)) (h : c • x ∈ A) : x ∈ A := by
  have hh := A.smul_mem h c⁻¹
  simpa only [smul_smul, inv_mul_cancel₀ hc, one_smul] using hh

theorem tensorModeBasis_one_mem_chevalley (w : K) (hw : w^4-w^2+1=0) (i : Fin 3) :
    tensorModeBasis w 1 i.castSucc ∈ chevalleyOperatorAlgebra w := by
  rw [← chevalleyE_inverse w hw i]
  exact (chevalleyOperatorAlgebra w).sum_mem (fun j _ =>
    (chevalleyOperatorAlgebra w).smul_mem (chevalleyE_mem_algebra w j) _)

theorem tensorModeBasis_neg_one_mem_chevalley (w : K) (hw : w^4-w^2+1=0) (i : Fin 3) :
    tensorModeBasis w (-1) i.castSucc ∈ chevalleyOperatorAlgebra w := by
  rw [← chevalleyF_inverse w hw i]
  exact (chevalleyOperatorAlgebra w).sum_mem (fun j _ =>
    (chevalleyOperatorAlgebra w).smul_mem (chevalleyF_mem_algebra w j) _)

private theorem shift_scalar_ne_zero (w : K) (hw : w^4-w^2+1=0)
    (r : Fin 2) (i : ℤ) (hi : i = 1 ∨ i = -1) :
    contraction w i.natAbs * rootWeight (w ^ (-i)) (simpleRoot r.castSucc.castSucc) ≠ 0 := by
  have hc : contraction w 1 ≠ 0 := contraction_ne_zero w hw ⟨1,by decide⟩
  apply mul_ne_zero
  · rcases hi with rfl | rfl <;> exact hc
  · rcases hi with rfl | rfl <;> fin_cases r <;>
      norm_num [Scalar.zpow_phasePolynomial w hw, Scalar.phasePolynomial,
        RootData.rootWeight_second] <;> intro hz <;> grind only

theorem simple_tensor_mode_mem_chevalley (w : K) (hw : w^4-w^2+1=0)
    (r : Fin 2) (n : ℤ) :
    tensorRootMode w (simpleRoot r.castSucc.castSucc) n ∈ chevalleyOperatorAlgebra w := by
  have hstep (j i : ℤ) (hi : i=1 ∨ i = -1)
      (hj : tensorRootMode w (simpleRoot r.castSucc.castSucc) j ∈ chevalleyOperatorAlgebra w) :
      tensorRootMode w (simpleRoot r.castSucc.castSucc) (j+i) ∈ chevalleyOperatorAlgebra w := by
    have hHi : heisenbergMode w i ∈ chevalleyOperatorAlgebra w := by
      rcases hi with rfl | rfl
      · exact tensorModeBasis_one_mem_chevalley w hw 2
      · exact tensorModeBasis_neg_one_mem_chevalley w hw 2
    have h := bracket_mem (chevalleyOperatorAlgebra w) hHi hj
    rw [heisenbergMode_tensorRootMode_lie] at h
    have hm : IsMode i.natAbs := by rcases hi with rfl | rfl <;> decide
    rw [if_pos hm] at h
    exact of_smul_mem _ _ (shift_scalar_ne_zero w hw r i hi) _ h
  refine Int.inductionOn' (motive := fun n =>
    tensorRootMode w (simpleRoot r.castSucc.castSucc) n ∈ chevalleyOperatorAlgebra w) n 1 ?_ ?_ ?_
  · fin_cases r
    · exact tensorModeBasis_one_mem_chevalley w hw 0
    · exact tensorModeBasis_one_mem_chevalley w hw 1
  · intro j _ hj
    exact hstep j 1 (Or.inl rfl) hj
  · intro j _ hj
    simpa only [sub_eq_add_neg] using hstep j (-1) (Or.inr rfl) hj

private theorem cPrime_ne_zero (w : K) (hw : w^4-w^2+1=0) : Scalar.cPrime w ≠ 0 := by
  intro h
  simp only [Scalar.cPrime] at h
  grind only

theorem heisenbergMode_mem_chevalley (w : K) (hw : w^4-w^2+1=0) (n : ℤ) :
    heisenbergMode w n ∈ chevalleyOperatorAlgebra w := by
  let A := chevalleyOperatorAlgebra w
  by_cases hn : n = 0
  · subst n; rw [heisenbergMode_zero]; exact A.zero_mem
  have h0 := simple_tensor_mode_mem_chevalley w hw 0 0
  have hn0 := simple_tensor_mode_mem_chevalley w hw 0 n
  have hn1 := simple_tensor_mode_mem_chevalley w hw 1 n
  change tensorRootMode w (simpleRoot 0) 0 ∈ A at h0
  change tensorRootMode w (simpleRoot 0) n ∈ A at hn0
  change tensorRootMode w (simpleRoot 1) n ∈ A at hn1
  have h := bracket_mem A h0 hn0
  rw [tensorFirstRoot_lie w hw] at h
  simp only [zero_add, Int.cast_zero, zpow_zero, mul_one, if_neg hn] at h
  have hs : (Scalar.cPrime w / 6) • heisenbergMode w n ∈ A := by
    have ht := A.sub_mem (A.add_mem (A.smul_mem hn0
      (Coefficients.pCoeff w * (w ^ (-2*(0:ℤ)+2*n) - w ^ (2*(0:ℤ)-2*n)) / 12))
      (A.smul_mem hn1 (Scalar.rootSecondResidue w * (w ^ (4*(0:ℤ)+9*n) - w ^ (9*(0:ℤ)+4*n)) / 12))) h
    simpa only [add_zero, sub_sub_cancel] using ht
  exact of_smul_mem A _ (div_ne_zero (cPrime_ne_zero w hw) (by norm_num)) _ hs

end KanadeRussell.Tsuchioka.Fock
