"""Generate exact-type checks for the completed portion of the frozen specification.

Every original target is proved; any future unproved target names are printed explicitly.
The production definitions must match the independent specification text exactly.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / 'Comparator' / 'KanadeRussell.lean'
DEFS = ROOT / 'KanadeRussell' / 'Source' / 'Defs.lean'
PROVED = {
    'isUnit_qPochhammer_q', 'summable_sourceTerm', 'hasProd_P9',
    'K₁_mul', 'K₂_mul', 'K₃_mul', 'constantCoeff_eq_one',
    'sourceNorm', 'kanade_russell_of_lowerBounds_of_productNorm',
    'kanade_russell_of_lowerBounds',
    'kanade_russell₁', 'kanade_russell₂', 'kanade_russell₃',
    'kanade_russell_hasSum₁', 'kanade_russell_hasSum₂', 'kanade_russell_hasSum₃',
}


def definitions(text):
    return dict(re.findall(
        r'^((?:noncomputable )?(?:def|abbrev) (\S+).*?)(?=\n\n)', text,
        re.M | re.S))


def main():
    spec = SPEC.read_text(encoding='utf-8-sig')
    prod = DEFS.read_text(encoding='utf-8-sig')
    for name in ('LowerBounds', 'ProductNorm'):
        prod += '\n' + (ROOT / 'KanadeRussell' / 'Pending' / (name + '.lean')).read_text(encoding='utf-8-sig')
    for body, name in definitions(spec).items():
        if body not in prod:
            raise SystemExit('Production definition differs from specification: ' + name)
    targets = re.findall(r'^theorem (\S+)(.*?):= by\s+sorry(?=\s)', spec, re.M | re.S)
    actual = {name for name, _ in targets}
    if not PROVED <= actual:
        raise SystemExit('Unknown submitted names: ' + repr(PROVED - actual))
    lines = ['import KanadeRussell', '',
             '/-! Exact frozen-comparator types for completed targets only.',
             f'Generated by scripts/check-comparator.py; {len(actual - PROVED)} targets remain open. -/', '',
             'open PowerSeries PowerSeries.WithPiTopology',
             'open scoped DiscreteUniformity QTheory', '',
             'namespace KanadeRussell.Submitted', '']
    for name, typ in targets:
        if name in PROVED:
            lines += [f'theorem {name}{typ}:= by', f'  exact KanadeRussell.{name}' + {'kanade_russell_of_lowerBounds': ' h', 'isUnit_qPochhammer_q': ' d m', 'summable_sourceTerm': ' a b', 'hasProd_P9': ' r', 'kanade_russell_of_lowerBounds_of_productNorm': " h h'"}.get(name, ''), '']
    lines += ['end KanadeRussell.Submitted', '']
    output = ROOT / 'Comparator' / 'Solution.lean'
    content = '\n'.join(lines)
    if '--write' in sys.argv:
        output.write_text(content, encoding='utf-8')
    elif not output.exists() or output.read_text(encoding='utf-8-sig') != content:
        raise SystemExit('Solution is stale; run python scripts/check-comparator.py --write')
    print(f'Exact specification coverage: {len(PROVED)}/{len(actual)} targets')
    for name, _ in targets:
        if name not in PROVED:
            print('OPEN: ' + name)


if __name__ == '__main__':
    main()
