import Mathlib

/-!
# Exact cyclotomic coefficients in Tsuchioka's straightening relations

Source: arXiv:2211.12351v3, Sections 3.2 and 4.3--4.9.
The root w satisfies the twelfth cyclotomic polynomial. All identities below
hold in any characteristic-zero field. The sign of the cubic term of c60 is
corrected from Section 4.3, consistently with the definition G6 = G4 - (P/Q) G5.

Generated by scripts/generate-tsuchioka-coefficients.py. The certificates are
polynomial identities checked by Lean, not imported results from the generator.
-/

namespace KanadeRussell.Tsuchioka.Coefficients

variable {K : Type*} [Field K] [CharZero K] (w : K)

omit [CharZero K] in
theorem pow_twelve (hw : w ^ 4 - w ^ 2 + 1 = 0) : w ^ 12 = 1 := by
  linear_combination (w ^ 8 + w ^ 6 - w ^ 2 - 1) * hw

theorem q_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : -4 * w ^ 2 + 2 ≠ 0 := by
  have h : (-4 * w ^ 2 + 2) * ((1 / 3) * w ^ 2 - (1 / 6)) = 1 := by
    linear_combination (-(4 / 3)) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem m_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : 4 * w ^ 3 - 8 * w - 6 ≠ 0 := by
  have h : (4 * w ^ 3 - 8 * w - 6) * ((1 / 3) * w ^ 3 - (2 / 3) * w + (1 / 2)) = 1 := by
    linear_combination ((4 / 3) * w ^ 2 - 4) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem t_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : 14 * w ^ 3 - 28 * w - 24 ≠ 0 := by
  have h : (14 * w ^ 3 - 28 * w - 24) * ((7 / 6) * w ^ 3 - (7 / 3) * w + 2) = 1 := by
    linear_combination ((49 / 3) * w ^ 2 - 49) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem f2_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : 2 * w ^ 3 - 4 * w - 2 ≠ 0 := by
  have h : (2 * w ^ 3 - 4 * w - 2) * ((1 / 4) * w ^ 3 - (1 / 2) * w + (1 / 4)) = 1 := by
    linear_combination ((1 / 2) * w ^ 2 - (3 / 2)) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem f3_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : -8 * w ^ 3 + 16 * w + 16 ≠ 0 := by
  have h : (-8 * w ^ 3 + 16 * w + 16) * ((1 / 8) * w ^ 3 - (1 / 4) * w + (1 / 4)) = 1 := by
    linear_combination (-w ^ 2 + 3) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem f4_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : -(1 / 3) * w ^ 3 + (2 / 3) * w ≠ 0 := by
  have h : (-(1 / 3) * w ^ 3 + (2 / 3) * w) * (-w ^ 3 + 2 * w) = 1 := by
    linear_combination ((1 / 3) * w ^ 2 - 1) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

theorem f5_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : -(1 / 3) * w ^ 3 + (2 / 3) * w + 1 ≠ 0 := by
  have h : (-(1 / 3) * w ^ 3 + (2 / 3) * w + 1) * ((1 / 2) * w ^ 3 - w + (3 / 2)) = 1 := by
    linear_combination (-(1 / 6) * w ^ 2 + (1 / 2)) * hw
  intro heq
  rw [heq, zero_mul] at h
  exact zero_ne_one h

omit [CharZero K] in
theorem pq_ratio_mul (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    4 * w ^ 5 - 10 * w ^ 3 - 8 * w ^ 2 + 4 * w + 4 = -6 * w ^ 3 - 8 * w ^ 2 + 4 := by
  linear_combination (4 * w) * hw

omit [CharZero K] in
theorem tm_ratio_mul (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    -4 * w ^ 6 + 16 * w ^ 4 + 14 * w ^ 3 - 16 * w ^ 2 - 28 * w - 12 = 14 * w ^ 3 - 28 * w - 24 := by
  linear_combination (-4 * w ^ 2 + 12) * hw

theorem f3_coefficient (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    (2 / 3) * w ^ 9 - 4 * w ^ 7 + (10 / 3) * w ^ 6 + 8 * w ^ 5 - (40 / 3) * w ^ 4 - (46 / 3) * w ^ 3 + (40 / 3) * w ^ 2 + 20 * w + 6 = -8 * w ^ 3 + 16 * w + 16 := by
  linear_combination ((2 / 3) * w ^ 5 - (10 / 3) * w ^ 3 + (10 / 3) * w ^ 2 + 4 * w - 10) * hw

theorem f4_coefficient (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    (208 / 3) * w ^ 16 + (208 / 3) * w ^ 15 - (472 / 3) * w ^ 14 - (652 / 3) * w ^ 13 + (112 / 3) * w ^ 12 + (472 / 3) * w ^ 11 + 48 * w ^ 10 - (152 / 3) * w ^ 6 - (208 / 3) * w ^ 5 + (248 / 3) * w ^ 4 + (388 / 3) * w ^ 3 + (112 / 3) * w ^ 2 + (56 / 3) * w + 48 = -(104 / 3) * w ^ 16 - (104 / 3) * w ^ 15 + (236 / 3) * w ^ 14 + (284 / 3) * w ^ 13 - (56 / 3) * w ^ 12 - (152 / 3) * w ^ 11 + (76 / 3) * w ^ 6 + (104 / 3) * w ^ 5 - (124 / 3) * w ^ 4 - (236 / 3) * w ^ 3 - (56 / 3) * w ^ 2 + (56 / 3) * w := by
  linear_combination (104 * w ^ 12 + 104 * w ^ 11 - 132 * w ^ 10 - 208 * w ^ 9 - 180 * w ^ 8 - 104 * w ^ 7 + 104 * w ^ 5 + 180 * w ^ 4 + 208 * w ^ 3 + 104 * w ^ 2 + 48) * hw

theorem f5_coefficient (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    (4 / 3) * w ^ 6 - (16 / 3) * w ^ 4 + (8 / 3) * w ^ 3 + (16 / 3) * w ^ 2 - (16 / 3) * w - 8 = -(2 / 3) * w ^ 6 + (8 / 3) * w ^ 4 + (8 / 3) * w ^ 3 - (8 / 3) * w ^ 2 - (16 / 3) * w - 2 := by
  linear_combination (2 * w ^ 2 - 6) * hw

/-- The leading unordered quadratic coefficient after factoring out the
nonzero common phase. The argument is (A-B) mod 12. -/
def orderingCoefficient (r : Fin 12) : K :=
  (-24 - 28 * w + 14 * w ^ 3) * (w ^ ((4 * r.val) % 12) + w ^ ((9 * r.val) % 12)) -
  (-52 + 104 * w ^ 2 + 90 * w ^ 3) * (w ^ ((4 * r.val) % 12) - w ^ ((9 * r.val) % 12))

/-- The leading coefficient vanishes exactly in the exceptional class.
These twelve residue classes cover every pair of integer indices. -/
theorem orderingCoefficient_eq_zero_iff (hw : w ^ 4 - w ^ 2 + 1 = 0) (r : Fin 12) :
    orderingCoefficient w r = 0 ↔ r.val = 7 := by
  fin_cases r
  · have hn : orderingCoefficient w 0 ≠ 0 := by
      have h : orderingCoefficient w 0 * ((7 / 12) * w ^ 3 - (7 / 6) * w + 1) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination ((49 / 3) * w ^ 2 - 49) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 1 ≠ 0 := by
      have h : orderingCoefficient w 1 * ((19 / 24) * w ^ 3 - (13 / 12) * w ^ 2 + (7 / 24) * w + (7 / 24)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination ((247 / 3) * w ^ 11 - (91 / 3) * w ^ 10 - (133 / 6) * w ^ 9 + (1 / 2) * w ^ 8 - (179 / 3) * w ^ 6 + (49 / 6) * w ^ 4 - w ^ 2 - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 2 ≠ 0 := by
      have h : orderingCoefficient w 2 * (-w ^ 3 + (7 / 12) * w ^ 2 + w - (7 / 6)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (76 * w ^ 10 + (179 / 3) * w ^ 9 - (410 / 3) * w ^ 8 - (130 / 3) * w ^ 7 + (269 / 3) * w ^ 6 - w ^ 2 - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 3 ≠ 0 := by
      have h : orderingCoefficient w 3 * (-(1 / 3) * w ^ 3 + (11 / 12) * w ^ 2 - (11 / 12) * w + (1 / 3)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (-(104 / 3) * w ^ 5 + (182 / 3) * w ^ 4 - (76 / 3) * w ^ 3 + 25 * w ^ 2 - 35 * w + (25 / 3)) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 4 ≠ 0 := by
      have h : orderingCoefficient w 4 * ((19 / 12) * w ^ 3 - (11 / 8) * w ^ 2 - (19 / 24) * w + (11 / 8)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (-(361 / 3) * w ^ 6 - (361 / 6) * w ^ 5 + (77 / 2) * w ^ 4 + (1 / 2) * w ^ 3 + (985 / 6) * w ^ 2 + (65 / 3) * w - (211 / 2)) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 5 ≠ 0 := by
      have h : orderingCoefficient w 5 * (-(7 / 12) * w ^ 3 - (7 / 12) * w ^ 2 + (13 / 6) * w - (19 / 12)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (-(182 / 3) * w ^ 11 - 77 * w ^ 10 + (676 / 3) * w ^ 9 - (130 / 3) * w ^ 8 + w ^ 6 - w ^ 2 - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 6 ≠ 0 := by
      have h : orderingCoefficient w 6 * (-(15 / 4) * w ^ 3 + (13 / 3) * w ^ 2 - (13 / 6)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (-390 * w ^ 8 + (182 / 3) * w ^ 7 + (497 / 3) * w ^ 6 - w ^ 5 + w ^ 4 - w ^ 3 + 285 * w ^ 2 + (182 / 3) * w - (185 / 3)) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hz : orderingCoefficient w 7 = 0 := by
      norm_num [orderingCoefficient]
      linear_combination (-76 * w ^ 3) * hw
    simpa using hz
  · have hn : orderingCoefficient w 8 ≠ 0 := by
      have h : orderingCoefficient w 8 * (-(13 / 6) * w ^ 3 + (15 / 4) * w ^ 2 - (13 / 6) * w) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination ((494 / 3) * w ^ 10 - (179 / 3) * w ^ 9 + w ^ 6 - w ^ 5 + w ^ 4 - w ^ 3 - (676 / 3) * w ^ 2 + (494 / 3) * w - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 9 ≠ 0 := by
      have h : orderingCoefficient w 9 * ((13 / 6) * w ^ 3 - (19 / 12) * w ^ 2 - (19 / 12) * w + (13 / 6)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination ((676 / 3) * w ^ 11 + (182 / 3) * w ^ 10 - (494 / 3) * w ^ 9 + w ^ 8 - w ^ 4 - (497 / 3) * w ^ 2 - 105 * w + (179 / 3)) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 10 ≠ 0 := by
      have h : orderingCoefficient w 10 * (-(19 / 24) * w ^ 2 + (11 / 8) * w - (19 / 24)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (-(247 / 3) * w ^ 7 + (182 / 3) * w ^ 6 + (182 / 3) * w ^ 5 - (133 / 6) * w ^ 4 - w ^ 2 - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn
  · have hn : orderingCoefficient w 11 ≠ 0 := by
      have h : orderingCoefficient w 11 * (-(5 / 4) * w ^ 3 + (5 / 4) * w ^ 2 + (1 / 3) * w - (11 / 12)) = 1 := by
        norm_num [orderingCoefficient]
        linear_combination (95 * w ^ 10 + 35 * w ^ 9 - (76 / 3) * w ^ 8 + (2 / 3) * w ^ 6 - 130 * w ^ 5 + (1 / 3) * w ^ 4 + (209 / 3) * w ^ 3 - w ^ 2 - 1) * hw
      intro hz
      rw [hz, zero_mul] at h
      exact zero_ne_one h
    simpa using hn

def pCoeff : K := 4 - 8 * w ^ 2 - 6 * w ^ 3
def qCoeff : K := 2 - 4 * w ^ 2
def mCoeff : K := -6 - 8 * w + 4 * w ^ 3
def tCoeff : K := -24 - 28 * w + 14 * w ^ 3

theorem qCoeff_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : qCoeff w ≠ 0 := by
  convert q_ne_zero w hw using 1; dsimp [qCoeff]; ring

theorem mCoeff_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) : mCoeff w ≠ 0 := by
  convert m_ne_zero w hw using 1; dsimp [mCoeff]; ring

theorem pq_ratio (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    pCoeff w / qCoeff w = 2 + 2 * w - w ^ 3 := by
  apply (div_eq_iff (qCoeff_ne_zero w hw)).mpr
  dsimp [pCoeff, qCoeff]
  linear_combination -pq_ratio_mul w hw

theorem tm_ratio (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    tCoeff w / mCoeff w = 2 + 2 * w - w ^ 3 := by
  apply (div_eq_iff (mCoeff_ne_zero w hw)).mpr
  dsimp [tCoeff, mCoeff]
  linear_combination -tm_ratio_mul w hw

/-- The corrected constant coefficient of G6, derived from its definition. -/
theorem c60_corrected (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    1 - pCoeff w / qCoeff w = -1 - 2 * w + w ^ 3 := by
  rw [pq_ratio w hw]
  ring

/-- The nonzero leading coefficient in the F2 combination. -/
theorem f2_coefficient (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    2 * (1 - tCoeff w / mCoeff w) = 2 * (-1 - 2 * w + w ^ 3) := by
  rw [tm_ratio w hw]
  ring

/-- The F3 combination, with the constant coefficient dictated by G6. -/
theorem f3_coefficient_from_ratios (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    (1 - pCoeff w / qCoeff w) *
      ((1 + (-4 * w + 2 * w ^ 3) / 3) -
        tCoeff w / mCoeff w * (1 + (6 - 4 * w + 2 * w ^ 3) / 3)) +
    (1 - tCoeff w / mCoeff w) *
      ((1 - pCoeff w / qCoeff w) - (4 * w - 2 * w ^ 3) / 3) =
    8 * (2 + 2 * w - w ^ 3) := by
  rw [pq_ratio w hw, tm_ratio w hw]
  linear_combination f3_coefficient w hw

/-- The phase cancellation in the repaired exceptional F1 relation.
After factoring out w^B, these are the coefficients of the second root
family in the relations at (A,B) and (A-1,B+1), when A-B is 7 mod 12. -/
theorem exceptional_phase_cancellation (hw : w ^ 4 - w ^ 2 + 1 = 0) :
    w ^ 4 - w ^ 3 = w ^ 9 - w ^ 10 := by
  linear_combination (w ^ 6 - w ^ 5 + w ^ 4 - w ^ 3) * hw



end KanadeRussell.Tsuchioka.Coefficients
