import KanadeRussell.Tsuchioka.Fock

/-!
Exact Fourier coefficients of the proved D4 Coxeter pairing sequence.
Generated by scripts/generate-tsuchioka-contractions.py.
The generator supplies polynomial certificates; Lean checks every identity.
-/

set_option backward.isDefEq.respectTransparency false

namespace KanadeRussell.Tsuchioka.Fock

variable {K : Type*} [Field K] [CharZero K] (w : K)

/-- Values of the first-root spectral pairing in the twelve residue classes. -/
def spectralValue (r : Fin 12) : K :=
  if r.val = 1 ∨ r.val = 11 then -w ^ 3 / 6 + w / 3 + 1 / 2
  else if r.val = 5 ∨ r.val = 7 then w ^ 3 / 6 - w / 3 + 1 / 2
  else 0

theorem contraction_fin (hw : w ^ 4 - w ^ 2 + 1 = 0) (r : Fin 12) :
    contraction w r.val = spectralValue w r := by
  fin_cases r
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    linear_combination ((1 / 12) * w ^ 7 + (1 / 12) * w ^ 6 + (1 / 12) * w ^ 5 - (1 / 12) * w ^ 3 - (1 / 4) * w ^ 2 - (1 / 4) * w - (1 / 3)) * hw
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    linear_combination (-(1 / 12) * w ^ 7 + (1 / 12) * w ^ 6 - (1 / 12) * w ^ 5 + (1 / 12) * w ^ 3 - (1 / 4) * w ^ 2 + (1 / 4) * w - (1 / 3)) * hw
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    linear_combination (-(1 / 12) * w ^ 7 + (1 / 12) * w ^ 6 - (1 / 12) * w ^ 5 + (1 / 12) * w ^ 3 - (1 / 4) * w ^ 2 + (1 / 4) * w - (1 / 3)) * hw
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    ring
  · norm_num [contraction, orbitPairing_eq, Fin.sum_univ_succ, spectralValue,
      Coefficients.zpow_mod_twelve w hw, Int.toNat]
    linear_combination ((1 / 12) * w ^ 7 + (1 / 12) * w ^ 6 + (1 / 12) * w ^ 5 - (1 / 12) * w ^ 3 - (1 / 4) * w ^ 2 - (1 / 4) * w - (1 / 3)) * hw

theorem contraction_mod_twelve (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    contraction w n = contraction w (n % 12) := by
  unfold contraction
  congr 1
  apply Finset.sum_congr rfl
  intro p hp
  congr 1
  apply Coefficients.zpow_eq_of_mod w hw
  have hn : Int.ModEq 12 (n : ℤ) ((n % 12 : ℕ) : ℤ) := by
    simp [Int.ModEq]
  exact (Int.ModEq.mul_right (p.val : ℤ) hn).neg

theorem spectralValue_eq_zero_iff (hw : w ^ 4 - w ^ 2 + 1 = 0) (r : Fin 12) :
    spectralValue w r = 0 ↔ ¬IsMode r.val := by
  have ha : (-w ^ 3 / 6 + w / 3 + 1 / 2) ≠ 0 := by
    have h : (-w ^ 3 / 6 + w / 3 + 1 / 2) * (w ^ 3 - 2 * w + 3) = 1 := by
      linear_combination (-(1 / 6) * w ^ 2 + (1 / 2)) * hw
    intro hz
    rw [hz, zero_mul] at h
    exact zero_ne_one h
  have hb : (w ^ 3 / 6 - w / 3 + 1 / 2) ≠ 0 := by
    have h : (w ^ 3 / 6 - w / 3 + 1 / 2) * (-w ^ 3 + 2 * w + 3) = 1 := by
      linear_combination (-(1 / 6) * w ^ 2 + (1 / 2)) * hw
    intro hz
    rw [hz, zero_mul] at h
    exact zero_ne_one h
  fin_cases r <;> norm_num [spectralValue, IsMode, ha, hb]

/-- Precisely the four principal residue classes contribute nonzero first-root
Heisenberg pairings, for every natural index. -/
theorem contraction_eq_zero_iff (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    contraction w n = 0 ↔ ¬IsMode n := by
  let r : Fin 12 := ⟨n % 12, Nat.mod_lt n (by decide)⟩
  rw [contraction_mod_twelve w hw n,
    show contraction w (n % 12) = spectralValue w r from contraction_fin w hw r,
    spectralValue_eq_zero_iff w hw]
  simp [r, IsMode]

theorem contraction_ne_zero (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : Mode) :
    contraction w n.val ≠ 0 := by
  intro hz
  exact ((contraction_eq_zero_iff w hw n.val).mp hz) n.property

end KanadeRussell.Tsuchioka.Fock
