import KanadeRussell.Tsuchioka.HeisenbergSpanning

/-! Cyclicity for the concrete algebra generated by the Heisenberg action,
all root Z modes, the level scalar, and the principal derivation. -/

set_option backward.isDefEq.respectTransparency false

namespace KanadeRussell.Tsuchioka.Fock

variable {K : Type*} [Field K] [CharZero K]

theorem zCyclicSpan_seed (w : K) (seed : Space K) : seed ∈ zCyclicSpan w seed :=
  Submodule.subset_span ⟨1, (zOperatorAlgebra w).one_mem, rfl⟩

theorem zCyclicSpan_algebra_mem (w : K) (seed : Space K)
    (a : Module.End K (Space K)) (ha : a ∈ zOperatorAlgebra w)
    (f : Space K) (hf : f ∈ zCyclicSpan w seed) :
    a f ∈ zCyclicSpan w seed := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨b, hb, rfl⟩ := hf
    exact Submodule.subset_span ⟨a * b, (zOperatorAlgebra w).mul_mem ha hb, rfl⟩
  | zero => simp
  | add f g hf hg hif hig => simpa only [map_add] using (zCyclicSpan w seed).add_mem hif hig
  | smul c f hf hi => simpa only [map_smul] using (zCyclicSpan w seed).smul_mem c hi

theorem rootMode_mem_zCyclicSpan (w : K) (seed : Space K) (β : RootData.Root) (i : ℤ)
    (f : Space K) (hf : f ∈ zCyclicSpan w seed) :
    rootMode w β.val i f ∈ zCyclicSpan w seed :=
  zCyclicSpan_algebra_mem w seed _ (Algebra.subset_adjoin (Or.inl ⟨(β, i), rfl⟩)) f hf

theorem degreeOperator_mem_zCyclicSpan (w : K) (seed : Space K)
    (f : Space K) (hf : f ∈ zCyclicSpan w seed) :
    degreeOperator f ∈ zCyclicSpan w seed := by
  have hd : principalDerivation (K := K) ∈ zOperatorAlgebra w :=
    Algebra.subset_adjoin (Or.inr (by simp))
  have h := (zCyclicSpan w seed).neg_mem
    (zCyclicSpan_algebra_mem w seed principalDerivation hd f hf)
  simpa only [principalDerivation, LinearMap.neg_apply, neg_neg] using h

noncomputable def oscillatorZAlgebra (w : K) : Subalgebra K (Module.End K (Space K)) :=
  Algebra.adjoin K (zGenerators w ∪
    (Set.range (heisenbergPositive w) ∪ Set.range (heisenbergNegative (K := K))))

theorem zOperatorAlgebra_le_oscillatorZAlgebra (w : K) :
    zOperatorAlgebra w ≤ oscillatorZAlgebra w :=
  Algebra.adjoin_mono (fun _ h => Or.inl h)

theorem heisenbergPositive_mem_oscillatorZAlgebra (w : K) (n : Mode) :
    heisenbergPositive w n ∈ oscillatorZAlgebra w :=
  Algebra.subset_adjoin (Or.inr (Or.inl ⟨n, rfl⟩))

theorem heisenbergNegative_mem_oscillatorZAlgebra (w : K) (n : Mode) :
    heisenbergNegative n ∈ oscillatorZAlgebra w :=
  Algebra.subset_adjoin (Or.inr (Or.inr ⟨n, rfl⟩))

theorem heisenbergWord_mem_oscillatorZAlgebra (w : K) (u : List Mode) :
    heisenbergWord u ∈ oscillatorZAlgebra w := by
  induction u with
  | nil => exact (oscillatorZAlgebra w).one_mem
  | cons n u ih =>
    exact (oscillatorZAlgebra w).mul_mem (heisenbergNegative_mem_oscillatorZAlgebra w n) ih

noncomputable def oscillatorZCyclicSpan (w : K) (seed : Space K) : Submodule K (Space K) :=
  Submodule.span K ((fun a : Module.End K (Space K) => a seed) ''
    (oscillatorZAlgebra w : Set (Module.End K (Space K))))

theorem oscillatorZCyclicSpan_seed (w : K) (seed : Space K) :
    seed ∈ oscillatorZCyclicSpan w seed :=
  Submodule.subset_span ⟨1, (oscillatorZAlgebra w).one_mem, rfl⟩

theorem oscillatorZCyclicSpan_algebra_mem (w : K) (seed : Space K)
    (a : Module.End K (Space K)) (ha : a ∈ oscillatorZAlgebra w)
    (f : Space K) (hf : f ∈ oscillatorZCyclicSpan w seed) :
    a f ∈ oscillatorZCyclicSpan w seed := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨b, hb, rfl⟩ := hf
    exact Submodule.subset_span ⟨a * b, (oscillatorZAlgebra w).mul_mem ha hb, rfl⟩
  | zero => simp
  | add f g hf hg hif hig =>
    simpa only [map_add] using (oscillatorZCyclicSpan w seed).add_mem hif hig
  | smul c f hf hi =>
    simpa only [map_smul] using (oscillatorZCyclicSpan w seed).smul_mem c hi

theorem zCyclicSpan_le_oscillatorZCyclicSpan (w : K) (seed : Space K) :
    zCyclicSpan w seed ≤ oscillatorZCyclicSpan w seed := by
  apply Submodule.span_le.mpr
  rintro _ ⟨a, ha, rfl⟩
  exact Submodule.subset_span ⟨a, zOperatorAlgebra_le_oscillatorZAlgebra w ha, rfl⟩

theorem oscillatorZAlgebra_preserves_heisenbergSpan (w : K) (seed : Space K)
    (hseed : seed ∈ heisenbergVacuum w)
    (a : Module.End K (Space K)) (ha : a ∈ oscillatorZAlgebra w) :
    ∀ f ∈ heisenbergSpan (zCyclicSpan w seed),
      a f ∈ heisenbergSpan (zCyclicSpan w seed) := by
  induction ha using Algebra.adjoin_induction with
  | mem a ha =>
    intro f hf
    rcases ha with hz | hp | hn
    · rcases hz with hz | hz
      · obtain ⟨⟨β, i⟩, rfl⟩ := hz
        exact rootMode_mem_heisenbergSpan w β.val i (zCyclicSpan w seed)
          (rootMode_mem_zCyclicSpan w seed β i) f hf
      · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
        rcases hz with rfl | rfl
        · exact (heisenbergSpan (zCyclicSpan w seed)).smul_mem 3 hf
        · exact (heisenbergSpan (zCyclicSpan w seed)).neg_mem
            (degreeOperator_mem_heisenbergSpan (zCyclicSpan w seed)
              (degreeOperator_mem_zCyclicSpan w seed) f hf)
    · obtain ⟨n, rfl⟩ := hp
      exact heisenbergPositive_mem_span w (zCyclicSpan w seed)
        (zCyclicSpan_le_heisenbergVacuum w seed hseed) n f hf
    · obtain ⟨n, rfl⟩ := hn
      exact heisenbergNegative_mem_span (zCyclicSpan w seed) n f hf
  | algebraMap c =>
    intro f hf
    exact (heisenbergSpan (zCyclicSpan w seed)).smul_mem c hf
  | add a b ha hb hia hib =>
    intro f hf
    exact (heisenbergSpan (zCyclicSpan w seed)).add_mem (hia f hf) (hib f hf)
  | mul a b ha hb hia hib =>
    intro f hf
    exact hia _ (hib f hf)

/-- Every vector in the combined cyclic action is a finite sum of negative
Heisenberg words applied to vectors in the Z-cyclic space. -/
theorem oscillatorZCyclicSpan_eq_heisenbergSpan (w : K) (seed : Space K)
    (hseed : seed ∈ heisenbergVacuum w) :
    oscillatorZCyclicSpan w seed = heisenbergSpan (zCyclicSpan w seed) := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro _ ⟨a, ha, rfl⟩
    exact oscillatorZAlgebra_preserves_heisenbergSpan w seed hseed a ha seed
      (le_heisenbergSpan _ (zCyclicSpan_seed w seed))
  · apply heisenbergSpan_le
    · exact zCyclicSpan_le_oscillatorZCyclicSpan w seed
    · intro n f hf
      exact oscillatorZCyclicSpan_algebra_mem w seed (heisenbergNegative n)
        (heisenbergNegative_mem_oscillatorZAlgebra w n) f hf

/-- Vacuum cyclicity is proved for the concrete combined oscillator--Z action.
Identifying that action with the affine standard-module action is a further step. -/
theorem oscillatorZCyclicSpan_inf_vacuum_eq_zCyclicSpan (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (seed : Space K) (hseed : seed ∈ heisenbergVacuum w) :
    oscillatorZCyclicSpan w seed ⊓ heisenbergVacuum w = zCyclicSpan w seed := by
  rw [oscillatorZCyclicSpan_eq_heisenbergSpan w seed hseed]
  exact heisenbergSpan_inf_vacuum_eq w hw _ (zCyclicSpan_le_heisenbergVacuum w seed hseed)

theorem oscillatorZCyclicSpan_vacuum_grade_eq_cyclicGrade (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    (oscillatorZCyclicSpan w 1 ⊓ heisenbergVacuum w) ⊓ grade (n : ℤ) =
      Partitions.cyclicGrade (highestWeightAction w) n := by
  rw [oscillatorZCyclicSpan_inf_vacuum_eq_zCyclicSpan w hw 1 (one_mem_heisenbergVacuum w),
    zCyclicSpan_vacuum_inf_grade_eq_cyclicGrade w hw]

theorem oscillatorZCyclicSpan_vacuum_grade_finite (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.Finite K ↥((oscillatorZCyclicSpan w 1 ⊓ heisenbergVacuum w) ⊓
      grade (n : ℤ) : Submodule K (Space K)) := by
  rw [oscillatorZCyclicSpan_vacuum_grade_eq_cyclicGrade w hw n]
  exact KanadeRussell.Straightening.fock_cyclicGrade_finite w hw n

theorem finrank_oscillatorZCyclicSpan_vacuum_grade_le_count (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.finrank K ↥((oscillatorZCyclicSpan w 1 ⊓ heisenbergVacuum w) ⊓
      grade (n : ℤ) : Submodule K (Space K)) ≤ Partitions.count 2 n := by
  rw [oscillatorZCyclicSpan_vacuum_grade_eq_cyclicGrade w hw n]
  exact KanadeRussell.Straightening.fock_finrank_le_count w hw n

end KanadeRussell.Tsuchioka.Fock
