import KanadeRussell.Tsuchioka.AllRootGeneration
import KanadeRussell.Tsuchioka.RootGeneration
import KanadeRussell.Straightening.FockPairs

/-! The concrete cyclic span of all D4 root modes has minimum-two admissible spanning.
Affine-module identification and the product character are separate obligations. -/

set_option backward.isDefEq.respectTransparency false

namespace KanadeRussell.Tsuchioka.Fock

variable {K : Type*} [Field K] [CharZero K]

theorem firstWordSpan_vacuum_eq_cyclicGrade (w : K) (n : ℕ) :
    firstWordSpan w 1 (-(n : ℤ)) =
      Partitions.cyclicGrade (highestWeightAction w) n := by
  have he (u : Word) :
      (highestWeightAction w).wordOperator u 1 = (highestWeightAction w).wordValue u := by
    change (highestWeightAction w).wordOperator u ((highestWeightAction w).wordValue []) = _
    rw [← HighestWeightAction.wordValue_append, List.append_nil]
  unfold firstWordSpan Partitions.cyclicGrade
  simp only [he]

theorem twoRootWordSpan_vacuum_eq_cyclicGrade (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    twoRootWordSpan w 1 (-(n : ℤ)) =
      Partitions.cyclicGrade (highestWeightAction w) n := by
  rw [twoRootWordSpan_eq_firstWordSpan w hw, firstWordSpan_vacuum_eq_cyclicGrade]

/-- Admissible first-root words span the concrete space generated by both
root families from the triple vacuum, in every degree. -/
theorem twoRootWordSpan_vacuum_eq_span_normal (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    twoRootWordSpan w 1 (-(n : ℤ)) = Submodule.span K
      (Set.range (fun u : Partitions.NormalWords 2 n =>
        (highestWeightAction w).wordValue u.val)) := by
  rw [twoRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_cyclicGrade_eq_span_normal w hw n

theorem twoRootWordSpan_vacuum_finite (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.Finite K (twoRootWordSpan w 1 (-(n : ℤ))) := by
  rw [twoRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_cyclicGrade_finite w hw n

/-- A dimension bound for the constructed cyclic span, without an assumed
representation character or product-coefficient identification. -/
theorem finrank_twoRootWordSpan_vacuum_le_count (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.finrank K (twoRootWordSpan w 1 (-(n : ℤ))) ≤ Partitions.count 2 n := by
  rw [twoRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_finrank_le_count w hw n


theorem allRootWordSpan_vacuum_eq_cyclicGrade (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    allRootWordSpan w 1 (-(n : ℤ)) =
      Partitions.cyclicGrade (highestWeightAction w) n := by
  rw [allRootWordSpan_eq_firstWordSpan w hw, firstWordSpan_vacuum_eq_cyclicGrade]

/-- The spanning statement includes the modes of every norm-two D4 root. -/
theorem allRootWordSpan_vacuum_eq_span_normal (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    allRootWordSpan w 1 (-(n : ℤ)) = Submodule.span K
      (Set.range (fun u : Partitions.NormalWords 2 n =>
        (highestWeightAction w).wordValue u.val)) := by
  rw [allRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_cyclicGrade_eq_span_normal w hw n

theorem allRootWordSpan_vacuum_finite (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.Finite K (allRootWordSpan w 1 (-(n : ℤ))) := by
  rw [allRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_cyclicGrade_finite w hw n

theorem finrank_allRootWordSpan_vacuum_le_count (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.finrank K (allRootWordSpan w 1 (-(n : ℤ))) ≤ Partitions.count 2 n := by
  rw [allRootWordSpan_vacuum_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_finrank_le_count w hw n

end KanadeRussell.Tsuchioka.Fock
