import KanadeRussell.Tsuchioka.ZCyclicGeneration
import KanadeRussell.Tsuchioka.RootCyclicSpanning

/-! Degree slices of the concrete Z-algebra cyclic space. Homogeneous projection
proves that no additional vectors enter a fixed degree from inhomogeneous sums. -/

set_option backward.isDefEq.respectTransparency false

namespace KanadeRussell.Tsuchioka.Fock

variable {K : Type*} [Field K] [CharZero K]

theorem firstWordSpan_le_firstCyclicSpan (w : K) (seed : Space K) (e : ℤ) :
    firstWordSpan w seed e ≤ firstCyclicSpan w seed := by
  apply Submodule.span_mono
  rintro _ ⟨u, hu, rfl⟩
  exact ⟨u, rfl⟩

theorem firstCyclicSpan_component_mem (w : K) (seed : Space K) (d n : ℤ)
    (hseed : seed ∈ grade d) (f : Space K) (hf : f ∈ firstCyclicSpan w seed) :
    MvPolynomial.weightedHomogeneousComponent variableWeight n f ∈
      firstWordSpan w seed (d - n) := by
  classical
  induction hf using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨u, rfl⟩ := hy
    rw [MvPolynomial.weightedHomogeneousComponent_of_mem
      (wordOperator_mem_grade w u d seed hseed)]
    split_ifs with hn
    · exact Submodule.subset_span ⟨u, by dsimp; omega, rfl⟩
    · exact Submodule.zero_mem _
  | zero => simp
  | add f g hf hg hif hig =>
    simpa only [map_add] using (firstWordSpan w seed (d - n)).add_mem hif hig
  | smul c f hf hi =>
    simpa only [map_smul] using (firstWordSpan w seed (d - n)).smul_mem c hi

/-- The fixed-index first-root span equals the actual degree slice of its
ungraded cyclic space. -/
theorem firstWordSpan_eq_inf_grade (w : K) (seed : Space K) (d n : ℤ)
    (hseed : seed ∈ grade d) :
    firstWordSpan w seed (d - n) = firstCyclicSpan w seed ⊓ grade n := by
  apply le_antisymm
  · intro f hf
    refine ⟨firstWordSpan_le_firstCyclicSpan w seed (d - n) hf, ?_⟩
    have hh := firstWordSpan_le_grade w seed d (d - n) hseed hf
    rwa [show d - (d - n) = n by ring] at hh
  · intro f hf
    have hh := firstCyclicSpan_component_mem w seed d n hseed f hf.1
    have he := MvPolynomial.IsWeightedHomogeneous.weightedHomogeneousComponent_same hf.2
    rw [he] at hh
    exact hh

theorem zCyclicSpan_inf_grade_eq_firstWordSpan (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (seed : Space K) (d n : ℤ) (hseed : seed ∈ grade d) :
    zCyclicSpan w seed ⊓ grade n = firstWordSpan w seed (d - n) := by
  rw [zCyclicSpan_eq_firstCyclicSpan w hw seed d hseed,
    firstWordSpan_eq_inf_grade w seed d n hseed]

theorem zCyclicSpan_vacuum_inf_grade_eq_cyclicGrade (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    zCyclicSpan w 1 ⊓ grade (n : ℤ) = Partitions.cyclicGrade (highestWeightAction w) n := by
  have h1 : (1 : Space K) ∈ grade 0 :=
    MvPolynomial.isWeightedHomogeneous_one K variableWeight
  rw [zCyclicSpan_inf_grade_eq_firstWordSpan w hw 1 0 n h1, zero_sub,
    firstWordSpan_vacuum_eq_cyclicGrade]

theorem zCyclicSpan_vacuum_grade_finite (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.Finite K ↥(zCyclicSpan w 1 ⊓ grade (n : ℤ) : Submodule K (Space K)) := by
  rw [zCyclicSpan_vacuum_inf_grade_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_cyclicGrade_finite w hw n

/-- The dimension bound now concerns the actual homogeneous slice of the
algebra generated by every root mode, the central scalar and the derivation. -/
theorem finrank_zCyclicSpan_vacuum_grade_le_count (w : K)
    (hw : w ^ 4 - w ^ 2 + 1 = 0) (n : ℕ) :
    Module.finrank K ↥(zCyclicSpan w 1 ⊓ grade (n : ℤ) : Submodule K (Space K)) ≤ Partitions.count 2 n := by
  rw [zCyclicSpan_vacuum_inf_grade_eq_cyclicGrade w hw]
  exact KanadeRussell.Straightening.fock_finrank_le_count w hw n

end KanadeRussell.Tsuchioka.Fock
